import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import charactersRouter from "./characters.js";
import questsRouter from "./quests.js";
import leaderboardRouter from "./leaderboard.js";
import battleRouter from "./battle.js";
import inventoryRouter from "./inventory.js";
import cultivateRouter from "./cultivate.js";
import guildsRouter from "./guilds.js";
import narrativeRouter from "./narrative.js";
import memoriesRouter from "./memories.js";
import worldStateRouter from "./worldState.js";
import skillsRouter from "./skills.js";
import factionsRouter from "./factions.js";
import marketRouter from "./market.js";
import worldEventsRouter from "./worldEvents.js";
import npcsRouter from "./npcs.js";
import worldCreatorRouter from "./worldCreator.js";
import multiverseRouter from "./multiverse.js";
import pvpRouter from "./pvp.js";
import achievementsRouter from "./achievements.js";
import dailyRouter from "./daily.js";
import dungeonRouter from "./dungeon.js";
import craftRouter from "./craft.js";
import guildWarRouter from "./guildWar.js";
import feedRouter from "./feed.js";
import godModeRouter from "./godMode.js";
import worldTradeRouter from "./worldTrade.js";
import worldPassportRouter from "./worldPassport.js";
import prophecyRouter from "./prophecy.js";
import isekaiRouter from "./isekai.js";
import fateRouter from "./fate.js";
import notificationsRouter from "./notifications.js";
import passwordResetRouter from "./passwordReset.js";
import emailVerificationRouter from "./emailVerification.js";
import auctionRouter from "./auction.js";
import titlesRouter from "./titles.js";
import petsRouter from "./pets.js";
import worldEconomyRouter from "./worldEconomy.js";
import diplomacyRouter from "./diplomacy.js";
import worldWarRouter from "./worldWar.js";
import worldThemeRouter from "./worldTheme.js";
import worldGovernanceRouter from "./worldGovernance.js";
import worldDisasterRouter from "./worldDisaster.js";
import bankRouter from "./bank.js";
import bountyRouter from "./bounty.js";
import tournamentRouter from "./tournament.js";
import realEstateRouter from "./realEstate.js";
import worldFairRouter from "./worldFair.js";
import citizenshipRouter from "./citizenship.js";
import expeditionRouter from "./expedition.js";
import worldSkillRouter from "./worldSkill.js";
import legendRouter from "./legend.js";
import worldFrameworkRouter from "./worldFramework.js";
import livingWorldRouter from "./livingWorld.js";
import multiWorldRouter from "./multiWorld.js";
import cosmicHierarchyRouter from "./cosmicHierarchy.js";
import worldWeatherRouter from "./worldWeather.js";
import worldSimulationRouter from "./worldSimulation.js";
import npcCoreRouter from "./npcCore.js";
import npcFamilyRouter from "./npcFamily.js";
import npcPopulationRouter from "./npcPopulation.js";
import npcFactionsRouter from "./npcFactions.js";
import territoriesRouter from "./territories.js";
import npcGovernmentRouter from "./npcGovernment.js";
import npcGovernmentPolicyRouter from "./npcGovernmentPolicy.js";
import npcElectionsRouter from "./npcElections.js";
import caravansRouter from "./caravans.js";
import knowledgeLibraryRouter from "./knowledgeLibrary.js";
import seasonalFestivalsRouter from "./seasonalFestivals.js";
import divineArenaRouter from "./divineArena.js";
import npcDiplomacyRouter from "./npcDiplomacy.js";
import militaryRouter from "./military.js";
import npcLongTermGoalsRouter from "./npcLongTermGoals.js";
import npcPlansRouter from "./npcPlans.js";
import npcEmotionsRouter from "./npcEmotions.js";
import personalityEvolutionRouter from "./personalityEvolution.js";
import npcDialogueRouter from "./npcDialogue.js";
import npcAgentRouter from "./npcAgent.js";
import worldAnalyticsRouter from "./worldAnalytics.js";
import stressTestRouter from "./stressTest.js";
import playerAgentRouter from "./playerAgent.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(charactersRouter);
router.use(questsRouter);
router.use(leaderboardRouter);
router.use(battleRouter);
router.use(inventoryRouter);
router.use(cultivateRouter);
router.use(guildsRouter);
router.use(narrativeRouter);
router.use(memoriesRouter);
router.use(worldStateRouter);
router.use(skillsRouter);
router.use(factionsRouter);
router.use(marketRouter);
router.use(worldEventsRouter);
router.use(npcsRouter);
router.use(worldCreatorRouter);
router.use(multiverseRouter);
router.use(pvpRouter);
router.use(achievementsRouter);
router.use(dailyRouter);
router.use(dungeonRouter);
router.use(craftRouter);
router.use(guildWarRouter);
router.use(feedRouter);
router.use(godModeRouter);
router.use(worldTradeRouter);
router.use(worldPassportRouter);
router.use(prophecyRouter);
router.use(isekaiRouter);
router.use(fateRouter);
router.use(notificationsRouter);
router.use(passwordResetRouter);
router.use(emailVerificationRouter);
router.use(auctionRouter);
router.use(titlesRouter);
router.use(petsRouter);
router.use(worldEconomyRouter);
router.use(diplomacyRouter);
router.use(worldWarRouter);
router.use(worldThemeRouter);
router.use(worldGovernanceRouter);
router.use(worldDisasterRouter);
router.use(bankRouter);
router.use(bountyRouter);
router.use(tournamentRouter);
router.use(realEstateRouter);
router.use(worldFairRouter);
router.use(citizenshipRouter);
router.use(expeditionRouter);
router.use(worldSkillRouter);
router.use(legendRouter);
router.use(worldFrameworkRouter);
router.use(livingWorldRouter);
router.use(multiWorldRouter);
router.use(cosmicHierarchyRouter);
router.use(worldWeatherRouter);
router.use(worldSimulationRouter);
router.use(npcCoreRouter);
router.use(npcFamilyRouter);
router.use(npcPopulationRouter);
router.use(npcFactionsRouter);
router.use(territoriesRouter);
router.use(npcGovernmentRouter);
router.use(npcGovernmentPolicyRouter);
router.use(npcElectionsRouter);
router.use(caravansRouter);
router.use(knowledgeLibraryRouter);
router.use(seasonalFestivalsRouter);
router.use(divineArenaRouter);
router.use(npcDiplomacyRouter);
router.use(militaryRouter);
router.use(npcLongTermGoalsRouter);
router.use(npcPlansRouter);
router.use(npcEmotionsRouter);
router.use(personalityEvolutionRouter);
router.use(npcDialogueRouter);
router.use(npcAgentRouter);
router.use(worldAnalyticsRouter);
router.use(stressTestRouter);
router.use(playerAgentRouter);

export default router;
